# Generated by Django 5.1.4 on 2024-12-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_userprogress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'UserProgress', 'verbose_name_plural': 'UserProgress'},
        ),
    ]
