BEGIN;
--
-- Create model Post
--
CREATE TABLE "posts_post" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "content" text NOT NULL, "author" varchar(70) NOT NULL, "published_date" timestamp with time zone NOT NULL);
COMMIT;
