BEGIN;
--
-- Create model Post
--
CREATE TABLE "posts_post" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "content" text NOT NULL, "author" varchar(70) NOT NULL, "published_date" timestamp with time zone NOT NULL);
COMMIT;

BEGIN;
--
-- Create model Category
--
CREATE TABLE "posts_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "description" text NOT NULL);
--
-- Add field category to post
--
CREATE TABLE "posts_post_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "post_id" bigint NOT NULL, "category_id" bigint NOT NULL);
--
-- Create model Comment
--
CREATE TABLE "posts_comment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "content" text NOT NULL, "post_id" bigint NOT NULL);
ALTER TABLE "posts_post_category" ADD CONSTRAINT "posts_post_category_post_id_category_id_c3f9067b_uniq" UNIQUE ("post_id", "category_id");
ALTER TABLE "posts_post_category" ADD CONSTRAINT "posts_post_category_post_id_87e52a7f_fk_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts_post" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "posts_post_category" ADD CONSTRAINT "posts_post_category_category_id_5ba3d77c_fk_posts_category_id" FOREIGN KEY ("category_id") REFERENCES "posts_category" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "posts_post_category_post_id_87e52a7f" ON "posts_post_category" ("post_id");
CREATE INDEX "posts_post_category_category_id_5ba3d77c" ON "posts_post_category" ("category_id");
ALTER TABLE "posts_comment" ADD CONSTRAINT "posts_comment_post_id_e81436d7_fk_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts_post" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "posts_comment_post_id_e81436d7" ON "posts_comment" ("post_id");
COMMIT;

BEGIN;
--
-- Change Meta options on category
--
-- (no-op)
--
-- Change Meta options on comment
--
-- (no-op)
--
-- Change Meta options on post
--
-- (no-op)
--
-- Add field image to post
--
ALTER TABLE "posts_post" ADD COLUMN "image" varchar(100) NULL;
COMMIT;
