services:
  django:
    build: django/.
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=assignment2
      - POSTGRES_USER=bauyrzhan
      - POSTGRES_PASSWORD=kbtu
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PYTHONUNBUFFERED=1
    networks:
      - net
    depends_on:
      - postgres
    volumes:
      - ./django:/usr/src/app
    
  postgres:
    image: postgres:16.4-bullseye
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=assignment2
      - POSTGRES_USER=bauyrzhan
      - POSTGRES_PASSWORD=kbtu
    networks:
      - net
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

networks:
  net:
    driver: bridge

# volumes:
#   assignment2:
