
services:
  django:
    build: django/.
    ports:
      - 8000:8000
    env_file: 
      - ./django.env
    command: 
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - net
    volumes:
      - ./django:/usr/src/app
    
  postgres:
    image: postgres:16.4-bullseye
    ports:
      - 5432:5432
    env_file: 
      - ./postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bauyrzhan -d midterm"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - net
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

networks:
  net:
    driver: bridge
