BEGIN;
--
-- Create model Question
--
CREATE TABLE "blogs_question" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question_text" varchar(200) NOT NULL, "pub_date" timestamp with time zone NOT NULL);
--
-- Create model Choice
--
CREATE TABLE "blogs_choice" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "choice_text" varchar(200) NOT NULL, "votes" integer NOT NULL, "question_id" bigint NOT NULL);
ALTER TABLE "blogs_choice" ADD CONSTRAINT "blogs_choice_question_id_c774bda9_fk_blogs_question_id" FOREIGN KEY ("question_id") REFERENCES "blogs_question" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blogs_choice_question_id_c774bda9" ON "blogs_choice" ("question_id");
COMMIT;
